/* Function Parser for C++ v4.0.5   

   Note: This file contains generated code and is thus not
   intended to be to be modified by hand. It was generated
   by util/bytecoderules_parser , which is available in the
   development package.

   Note: You don't need to add this file to your project. It's
   enough for it to be in the same directory as fparser.cc. This
   file is internally #included by fparser.cc.
*/
#define FP_TRACE_BYTECODE_OPTIMIZATION(srcline,from,to,with) \
    /*std::cout << "Changing \"" from "\"\t(line " #srcline ")\n" \
                   "    into \"" to "\"\n" with*/
#define FP_TRACE_OPCODENAME(op) \
    (op < VarBegin \
        ? FP_GetOpcodeName(OPCODE(op)) \
        : findName(data->namePtrs,op,NameData<Value_t>::VARIABLE))
#define qF1 x)gI Lnm;
#define qE1 wF"x"mD
#define qD1 wM","aF
#define qC1 qR y*x
#define qB1 "cSub"
#define qA1 mG"x "
#define q91 ", "wS q41
#define q81 qI h9 w1
#define q71 wM","mE
#define q61 ", "wS<<","m7
#define q51 "B[B>=VarBegin]"aG
#define q41 <<","aF
#define q31 wM","m7
#define q21 if(x>gN w1
#define q11 "[x]"wF
#define q01 ==h8 w1
#define aZ wP wJ
#define aY cExp:w1
#define aX "cSin"
#define aW "cCsc"
#define aV "cTan"
#define aU "cCot"
#define aT "cSec"
#define aS ==dY a8
#define aR "C "w3
#define aQ hW w1
#define aP if(gB w1
#define aO " cSub"
#define aN "cSinh"
#define aM "A[IsAlwaysIntegerOpcode(A)] "
#define aL "    "wN
#define aK " "mF
#define aJ " "wA w7
#define aI qJ hH w1
#define aH " "w6
#define aG " "mY
#define aF " "a2
#define aE gC cInv:
#define aD "cFloor"
#define aC "cExp"
#define aB qD h4 w1
#define aA "cInv"
#define a9 m1 qB1
#define a8 ){w1
#define a7 "cRDiv"
#define a6 "cCeil"
#define a5 wQ" "
#define a4 "cLess"
#define a3 a7 wT
#define a2 m1 w3
#define a1 =qS;qG w1
#define a0 "cMin"
#define mZ "cMax"
#define mY "cDiv"
#define mX x);g7
#define mW wY" x "wJ
#define mV qF d6 gI
#define mU "cSqrt"
#define mT aC" "
#define mS "[y*x]"
#define mR qW q21
#define mQ wJ" "
#define mP "cLog"
#define mO "cGreater"
#define mN g8 w1
#define mM wF wO mY
#define mL "cAbsNot"
#define mK "cLessOrEq"
#define mJ "cNotNot"
#define mI "[ y+x] "
#define mH " "wS wE
#define mG "y "
#define mF "cNeg"
#define mE " "wD
#define mD " "w7
#define mC "cCos"
#define mB "cAbs"
#define mA "cCosh"
#define m9 "[-x]"wF
#define m8 "cLog10"
#define m7 " "w4
#define m6 " cNot"
#define m5 "A "wU w7
#define m4 "cLog2"
#define m3 "cExp2"
#define m2 "cGreaterOrEq"
#define m1 "B "
#define m0 "cEqual"
#define wZ hP==d6 hQ w1
#define wY "cRSub"
#define wX "cSqr"
#define wW hP qL w1
#define wV " cPow"
#define wU "[x] "
#define wT " x"mD
#define wS "x = "<<x
#define wR "cNEqual"
#define wQ "B[B==A]"
#define wP "cDup "
#define wO "x[x!=Value_t(0)] "
#define wN "with"mE
#define wM "  "w2
#define wL "B[B>=VarBegin]"aO" x "wJ
#define wK "x[x>Value_t(0)]"
#define wJ "cAdd"
#define wI "B[IsNeverNegativeValueOpcode(B)] "
#define wH "x[IsIntegerConst(x)]"wV
#define wG "x[x==Value_t(1)] "
#define wF mD" "
#define wE <<"\n"
#define wD "A "w3
#define wC "B[IsBinaryOpcode(B)&&!HasInvalidRangesOpcode(B)] "w5
#define wB "A[IsNeverNegativeValueOpcode(A)] "
#define wA "A[A>=VarBegin] "
#define w9 wM"\n"
#define w8 "x[x==Value_t(0)] "
#define w7 "cMul"
#define w6 "x A[IsComparisonOpcode(A)]"
#define w5 "A[IsBinaryOpcode(A)&&!HasInvalidRangesOpcode(A)] "w8 w7
#define w4 mG"= "<<y wE
#define w3 "= "<<FP_TRACE_OPCODENAME
#define w2 "  with "wS<<
#define w1 FP_TRACE_BYTECODE_OPTIMIZATION
#define w0 cLog10
#define oZ cLog2
#define oY cSqrt:
#define oX cTanh
#define oW cAbs){
#define oV cSinh
#define oU qB y*x
#define oT qB x);
#define oS for q9
#define oR qP q6
#define oQ Immed
#define oP }if(
#define oO Lcm;oP
#define oN Lbo;
#define oM Laq;
#define oL ==A){
#define oK Default5
#define oJ Lao;
#define oI cAdd
#define oH fp_pow(
#define oG hF q1
#define oF q5 qP q1 d6
#define oE q5:x=qE;
#define oD q1 A gI
#define oC cRDiv:
#define oB qM q5);
#define oA TailCall_cAdd
#define o9 q1 A);
#define o8 cNEqual
#define o7 q3 Lcj;
#define o6 cLess:
#define o5 FP_ReDefinePointers();
#define o4 cSub:
#define o3 g7 qK
#define o2 .size()
#define o1 =q5;
#define o0 TailCall_cDiv
#define dZ q7 q4
#define dY cDup
#define dX fp_exp(x
#define dW opcode
#define dV TailCall_cEqual
#define dU ;if(
#define dT TailCall_cAbs
#define dS dM 3]dU
#define dR dM 3]){gC
#define dQ TailCall_cTan
#define dP q0 qO
#define dO q0 gF q3
#define dN TailCall_cSin
#define dM q0[-
#define dL g9 1]qC
#define dK dM 4]
#define dJ q5:qZ
#define dI qJ dJ
#define dH fp_exp2(x
#define dG qB qA(
#define dF Default7
#define dE Default6
#define dD Default3
#define dC Default1
#define dB fp_log(
#define dA cExp2
#define d9 cNotNot
#define d8 cEqual:
#define d7 cPow:
#define d6 cMul
#define d5 fp_log10(
#define d4 cAbs);
#define d3 [-3]o1 g2 q4 q3
#define d2 fp_abs(x)
#define d1 qF oI);
#define d0 break;
#define hZ fp_log2(
#define hY q6 g2 q4
#define hX B oL
#define hW hL hX
#define hV hL B qY
#define hU qM q5 gI
#define hT 0.5)){
#define hS cGreater
#define hR qH-2]
#define hQ ){hR qC
#define hP qH-1]
#define hO h1 hP==cRSub hQ
#define hN g6 0)){
#define hM incStackPtr();qX
#define hL B qV
#define hK oK;gC
#define hJ qE=-x;
#define hI oS 4 q8
#define hH cSqr:
#define hG switch(
#define hF data->
#define hE TailCall_cSub
#define hD TailCall_cNeg
#define hC cLessOrEq
#define hB unsigned
#define hA o1 q0
#define h9 cAbs:
#define h8 qA(1)){
#define h7 g5==h8
#define h6 ,x gI oJ
#define h5 cGreaterOrEq
#define h4 dY:
#define h3 TailCall_cNotNot
#define h2 gI Lmm;
#define h1 if(A qY
#define h0 ,x gI oM
#define gZ ,y gI oM
#define gY gS hA-=2;dZ
#define gX oI:qH-
#define gW qI gX 2]
#define gV =q0[0];
#define gU q7 q1 d6);
#define gT g4 A gV
#define gS dM 2]
#define gR isEvenInteger(
#define gQ d0}
#define gP GetDegreesToRadiansFactor<qA>()){
#define gO GetRadiansToDegreesFactor<qA>()){
#define gN qA(0)){
#define gM gC dL if(x>gN
#define gL qR y+x oR
#define gK hF q4 q3
#define gJ dW=
#define gI );q3
#define gH ,y gI oJ
#define gG IsLogicalOpcode(A)){
#define gF -=1 qP q4
#define gE IsUnaryOpcode(
#define gD hF ByteCode
#define gC case
#define gB IsAlwaysIntegerOpcode(A)){
#define gA hI q1 d6);
#define g9 d6:qH-
#define g8 cNeg:
#define g7 return;
#define g6 if(x==qA(
#define g5 qH 0]qC if(x
#define g4 default:
#define g3 >=VarBegin&&gD o2>
#define g2 oS 3 q8
#define g1 hG gS){gC
#define g0 &&!HasInvalidRangesOpcode(
#define qZ y=q2[-1];
#define qY >=VarBegin){
#define qX --StackPtr;q3
#define qW gC oE
#define qV =gS dU
#define qU hL IsNeverNegativeValueOpcode(B)){
#define qT hF q6
#define qS dM 1]
#define qR q2[-1]=
#define qQ o5 q3
#define qP ;hF
#define qO gF gJ
#define qN q3 Default0;
#define qM gD.push_back(
#define qL ==q5){qZ
#define qK }}qN
#define qJ }d0 gC
#define qI hG qS){gC
#define qH if(q0[
#define qG if(IsNeverNegativeValueOpcode(A)){
#define qF AddFunctionOpcode(
#define qE q2[0]
#define qD hG q0[0]){gC
#define qC ==q5){x=qE;
#define qB hF oQ.push_back(
#define qA Value_t
#define q9 (hB tmp=
#define q8 ;tmp-->0;)hF
#define q7 oS 2 q8
#define q6 oQ.pop_back();
#define q5 cImmed
#define q4 ByteCode.pop_back();
#define q3 goto
#define q2 ImmedPtr
#define q1 q4 qF
#define q0 ByteCodePtr
hB*q0;qA*q2;
#define FP_ReDefinePointers() q0=!gD.empty()?&gD[0]+gD o2-1:0;q2=!hF oQ.empty()?&hF oQ[0]+hF oQ o2-1:0;
o5
#if(!FP_FLOAT_VERSION)
qA
x;hB
A;qA
y;hB
B;hB
C;hB
D;hG
dW){dT:gC
h9
qD
mN(236,mF" "
mB,mB,);q3
Laa;qW
w1(40,"x "
mB,"[fp_abs(x)]"
,w9);q3
Lab;gT
qG
w1(295,wB
mB,"A"
,aL(A)wE);o3
oA:gC
oI:qD
h4
gW
aS(186,wP
mQ
aZ,"[Value_t(4)]"
mD,);q3
Lac;qJ
g9
2]==oI){qH-3]aS(187,aZ
wF
aZ,w7" [Value_t(4)]"
mD,);q3
Lad;}
}
gQ
q3
dC;gC
dL
hR
aS(189,wP"x"
wF
wJ,"[x+Value_t(1)]"
mD,w9);q3
Lae;}
}
q3
dC;gC
mN(243,mF" "
wJ,qB1,);q3
Laf;qW
gW
qL
w1(180,mG
mQ"x "
wJ,"[y+x] "
wJ,q31);q3
Lag;qJ
cRSub:g1
gX
3]qL
w1(121,mG
mQ
mW,mI
mQ
wY,q31);q3
Lah;qJ
mN(122,mF" "
mW,"[-x] "
mQ
wY,w9);q3
Lai;gC
dJ
w1(120,mG
mW,mI
wY,q31);q3
Laj;qJ
o4
hV
hG
dR
gX
4]qL
w1(115,mG
mQ
wL,mI
mQ
a9,qD1(B)<<","
m7);q3
Lak;qJ
mN(116,mF" "
wL,"[-x] "
mQ
a9,qD1(B)wE);q3
Lal;gC
dJ
w1(114,mG
wL,mI
a9,qD1(B)<<","
m7);q3
Lam;}
dI
w1(76,qA1
wJ,"[y+x]"
,q31);q3
Lan;}
hN
w1(75,w8
wJ,,w9);q3
oJ}
d0
g4
dC:;A
gV
hO
w1(113,"x "
wY" "
wA
wJ,"[DO_STACKPLUS1] A "
wU
mQ
wY,aL(A)<<","
mH);hM
Lap;}
w1(118,wY" "
wA
wJ,"[DO_STACKPLUS1] A "
mQ
wY,aL(A)wE);hM
oM}
qK
TailCall_cAnd:gC
cAnd:qH
0]qC
wW(169,mG"x cAnd"
,"[fp_and(x,y)]"
,q31);q3
Lba;qK
o0:gC
cDiv:aB(159,wP
mY,"[Value_t(0)]"
wF"[Value_t(1)] "
wJ,);q3
Lbb;qW
if(x!=gN
qI
mN(177,mF" "
wO
mY,"[-x]"
aG,w9);q3
Lbc;gC
dJ
w1(73,mG
wO
mY,"[y/x]"
,q31);q3
Lbd;}
}
g6
1)a8(72,wG
mY,,w9);q3
oJ}
gQ
qN
dV:gC
d8
h7
A=qS
dU
gG
w1(323,"A[IsLogicalOpcode(A)] "
wG
m0,"A"
,q71(A)wE);q3
oJ}
}
wW(167,qA1
m0,"[fp_equal(y,x)]"
,q31);q3
Lbe;}
hN
q81(255,mB" "
w8
m0,wU
m0,w9);q3
Lbf;gC
hH
w1(257,wX" "
w8
m0,wU
m0,w9);q3
Lbf;}
w1(313,w8
m0,"cNot"
,w9);q3
Lbg;qK
TailCall_cGreater:gC
hS:g5==gN
q81(315,mB" "
w8
mO,mJ,w9);q3
Lbh;g4
A
a1(319,wB
w8
mO,"A "
mJ,q71(A)wE);q3
Lbi;}
}
}
wW(165,qA1
mO,"[fp_less(x,y)]"
,q31);q3
Lbj;qK
TailCall_cGreaterOrEq:gC
h5:h7
q81(316,mB" "
wG
m2,mJ,w9);q3
Lbh;g4
A
a1(320,wB
wG
m2,"A "
mJ,q71(A)wE);q3
Lbi;}
}
}
wW(166,qA1
m2,"[fp_lessOrEq(x,y)]"
,q31);q3
Lbk;qK
TailCall_cInv:aE
qD
cInv:w1(237,aA" "
aA,,);q3
Lbl;gC
oY
w1(67,mU" "
aA,"cRSqrt"
,);q3
Lbm;qW
if(x!=gN
w1(69,wO
aA,"[Value_t(1)/x]"
,w9);q3
Lbn;}
gQ
qN
TailCall_cLess:gC
o6
g5==gN
A
a1(124,wB
w8
a4,m5,q71(A)wE);q3
oN}
}
g6
1)){q81(317,mB" "
wG
a4,"cNot"
,w9);q3
Lbp;g4
A
a1(321,wB
wG
a4,"A"
m6,q71(A)wE);q3
Lbg;}
}
}
wW(163,qA1
a4,"[fp_less(y,x)]"
,q31);q3
Lbq;qK
TailCall_cLessOrEq:gC
hC:g5==gN
q81(318,mB" "
w8
mK,"cNot"
,w9);q3
Lbp;g4
A
a1(322,wB
w8
mK,"A"
m6,q71(A)wE);q3
Lbg;}
}
}
wW(164,qA1
mK,"[fp_lessOrEq(y,x)]"
,q31);q3
Lca;qK
TailCall_cMax:gC
cMax:aB(149,wP
mZ,,);q3
Lbl;qW
wW(82,qA1
mZ,"[fp_max(x,y)]"
,q31);q3
Lcb;}
d0
gT
h1
qI
h4
aQ(151,a5
wP
wA
mZ,m1"cDup"
,aL(A)q41(B)wE);q3
Lbl;qJ
cMax:aQ(153,a5
mZ" "
wA
mZ,m1
mZ,aL(A)q41(B)wE);q3
Lbl;}
gQ
qK
TailCall_cMin:gC
cMin:aB(148,wP
a0,,);q3
Lbl;qW
wW(81,qA1
a0,"[fp_min(x,y)]"
,q31);q3
Lcc;}
d0
gT
h1
qI
h4
aQ(150,a5
wP
wA
a0,m1"cDup"
,aL(A)q41(B)wE);q3
Lbl;qJ
cMin:aQ(152,a5
a0" "
wA
a0,m1
a0,aL(A)q41(B)wE);q3
Lbl;}
gQ
qK
TailCall_cMod:gC
cMod:g5!=gN
wW(74,mG
wO"cMod"
,"[fp_mod(y,x)]"
,q31);q3
Lcd;}
qK
TailCall_cMul:gC
d6:aB(396,wP
w7,wX,);q3
Lce;aE
w1(242,aA
mD,mY,);q3
Lcf;gC
g8
A=qS;h1
g1
d6:B=dS
hX
w1(388,wQ
wF
wA
mF
mD,m1
wX
wF
mF,aL(A)q41(B)wE);q3
Lcg;}
q3
Default2;g4
Default2:;aQ(382,a5
wA
mF
mD,m1
wX
aK,aL(A)q41(B)wE);q3
Lch;}
}
}
q3
dD;gC
d7
hP
qC
hR
aS(190,wP"x"
wV
mD,"[x+Value_t(1)]"
wV,w9);q3
Lci;}
}
q3
dD;qW
hN
qI
d6:A
qV
A
qY
w1(133,wA
w7" "
w8
w7,wU
w7,q71(A)wE);o7}
q3
Default4;g4
Default4:;A=qS
dU
IsBinaryOpcode(A)g0
A)){g1
dJ
w1(132,mG
w5,wU
w7,q71(A)<<","
m7);q3
Lck;g4
hL
IsBinaryOpcode(B)g0
B)){hG
dR
dJ
w1(136,mG
wC,m5,q71(A)q41(B)<<","
m7);q3
Lcl;g4
C=dS
C
qY
w1(134,"C[C>=VarBegin] "
wC,m5,q71(A)q41(B)<<", "
aR(C)wE);q3
oO
gE
C)g0
C)a8(135,"C[IsUnaryOpcode(C)&&!HasInvalidRangesOpcode(C)] "
wC,m1
m5,q71(A)q41(B)<<", "
aR(C)wE);q3
Lcn;}
}
oP
B
qY
w1(130,"B[B>=VarBegin] "
w5,wU
w7,q71(A)q41(B)wE);o7
oP
gE
B)g0
B)a8(131,"B[IsUnaryOpcode(B)&&!HasInvalidRangesOpcode(B)] "
w5,m5,q71(A)q41(B)wE);q3
Lco;}
}
}
h1
w1(128,wA
w8
w7,"[x]"
,q71(A)wE);q3
Lcp;oP
gE
A)g0
A)a8(129,"A[IsUnaryOpcode(A)&&!HasInvalidRangesOpcode(A)] "
w8
w7,wU
w7,q71(A)wE);q3
Lcq;}
}
}
qI
oI:g1
h4
w1(194,aZ
wT,"[x+x]"
mD,w9);q3
Lda;gC
g9
3]qL
A=dK;h1
w1(282,wA"y"
wF
wJ
wT,q11"A "
mS
wF
wJ,wM", "
mG"= "
<<y<<","
mE(A)wE);q3
Ldb;}
dI
w1(281,mG
wJ
wT,q11
mS" "
wJ,q31);q3
Ldc;qJ
d6:g1
gX
3]aS(196,aZ
qE1,w7" [x+x]"
mD,w9);q3
Ldd;dI
if(y*x
q01(184,"y[y*x==Value_t(1)]"
qE1,,q31);q3
Lde;}
w1(185,"y"
qE1,mS
mD,q31);q3
Ldf;qJ
mN(174,mF
wT,"[-x]"
mD,w9);q3
Ldg;gC
o4
hR==d6){qH-3]qL
A=dK;h1
w1(283,wA"y"
wF
qB1
wT,q11"A "
mS
wF
qB1,wM", "
mG"= "
<<y<<","
mE(A)wE);q3
Ldh;}
}
dI
w1(71,"y"
wT,mS,q31);q3
Ldi;}
g6
1)a8(70,wG
w7,,w9);q3
oJ}
g6
2)a8(139,"x[x==Value_t(2)]"
mD,aZ,w9);q3
Ldj;}
g6-1)a8(176,"x[x==Value_t(-1)]"
mD,mF,w9);q3
Ldk;}
d0
g4
dD:;A
gV
h1
qI
d6:g1
g8
B=dS
hX
w1(385,a5
mF
wF
wA
w7,m1
wX
wF
mF,aL(A)q41(B)wE);q3
Lcg;}
q3
oK;g4
oK:;aQ(376,wQ
wF
wA
w7,m1
wX
mD,aL(A)q41(B)wE);q3
Ldl;}
}
q3
dE;gC
g8
aQ(379,a5
mF
aJ,m1
wX
aK,aL(A)q41(B)wE);q3
Lch;}
q3
dE;g4
dE:;B=qS
dU
hX
w1(373,a5
wA
w7,m1
wX,aL(A)q41(B)wE);q3
Lce;}
}
oP
gE
A)){B=qS
dU
B
g3
1){hR==d6){C=dS
C
oL
D=dK
dU
D==B
a8(395,"D[D==B] C[C==A]"
wF"B[B>=VarBegin&&data->ByteCode.size()>1] A[IsUnaryOpcode(A)]"
mD,"D C "
wX
mD,aL(A)q41(B)<<", "
aR(C)<<", D "
w3(D)wE);q3
Ldm;}
}
}
}
qK
TailCall_cNEqual:gC
o8:h7
A=qS
dU
gG
w1(324,"A[IsLogicalOpcode(A)] "
wG
wR,"A"
m6,q71(A)wE);q3
Lbg;}
}
wW(168,qA1
wR,"[fp_nequal(y,x)]"
,q31);q3
Ldn;}
hN
q81(256,mB" "
w8
wR,wU
wR,w9);q3
Ldo;gC
hH
w1(258,wX" "
w8
wR,wU
wR,w9);q3
Ldo;}
w1(314,w8
wR,mJ,w9);q3
Lbi;qK
hD:gC
g8
qD
dL
w1(175,"x"
wF
mF,"[-x]"
mD,w9);q3
Ldp;qJ
mN(238,mF
aK,,);q3
Lbl;qW
w1(68,"x"
aK,"[-x]"
,w9);q3
Ldq;}
qN
TailCall_cNot:gC
cNot:qD
h9
w1(286,mB
m6,"cNot"
,);q3
Lea;gC
cAbsNot:A=qS
dU
gG
w1(291,"A[IsLogicalOpcode(A)] "
mL
m6,"A"
,aL(A)wE);q3
Lbl;oP
A!=q5
a8(292,"A[A!=cImmed] "
mL
m6,"A cAbsNotNot"
,aL(A)wE);q3
Leb;}
q3
dF;gC
cAbsNotNot:w1(289,"cAbsNotNot"
m6,mL,);q3
Lec;gC
gX
1]qC
w1(326,"x "
wJ
m6,wU
m0,w9);q3
Led;}
q3
dF;gC
d8
w1(252,m0
m6,wR,);q3
Lee;gC
hS:w1(250,mO
m6,mK,);q3
Lef;gC
h5:w1(251,m2
m6,a4,);q3
Leg;gC
o6
w1(248,a4
m6,m2,);q3
Leh;gC
hC:w1(249,mK
m6,mO,);q3
Lei;gC
o8:w1(253,wR
m6,m0,);q3
Lej;gC
mN(285,mF
m6,"cNot"
,);q3
Lea;gC
cNot:w1(287,"cNot"
m6,mJ,);q3
Lek;gC
d9:w1(288,mJ
m6,"cNot"
,);q3
Lea;qW
w1(85,"x"
m6,"[fp_not(x)]"
,w9);q3
Lel;g4
dF:;A
gV
qG
w1(293,wB"cNot"
,"A "
mL,aL(A)wE);q3
Lem;qK
h3:gC
d9:qH
0]==oI){hP
qC
w1(325,"x "
mQ
mJ,wU
wR,w9);q3
Len;qK
TailCall_cOr:gC
cOr:qH
0]qC
wW(170,mG"x cOr"
,"[fp_or(x,y)]"
,q31);q3
Leo;qK
TailCall_cRDiv:gC
oC
h7
w1(91,wG
a7,aA,w9);q3
Lep;qK
TailCall_cSqr:gC
hH
qD
h9
w1(391,mB" "
wX,wX,);q3
Leq;gC
mN(390,mF" "
wX,wX,);q3
Leq;}
qN
hE:gC
o4
aB(191,wP
qB1,"[Value_t(0)]"
mD,);q3
Lfa;gC
mN(244,mF
aO,wJ,);q3
Lfb;qW
hN
w1(77,w8
qB1,,w9);q3
oJ}
wW(78,mG"x"
aO,"[y-x]"
,q31);q3
Lfc;}
w1(207,"x"
aO,"[-x] "
wJ,w9);q3
Lfd;gT
hO
w1(112,"x "
wY" "
wA
qB1,"A "
mQ
wU
wY,aL(A)<<","
mH);q3
Lfe;}
w1(119,wY" "
wA
qB1,"[DO_STACKPLUS1] A"
aO" "
wY,aL(A)wE);hM
Lff;}
qK
g4
Default0:;A=dW
dU
IsComparisonOpcode(A)){qH
0]qC
gW
qL
w1(260,mG
mQ
w6,"[x-y] A"
,aL(A)<<q61);q3
Lfg;qJ
mN(261,mF
aH,"[-x] {OppositeComparisonOpcode(A)}"
,aL(A)<<","
mH);q3
Lfh;}
}
oP
A
g3
0){B
gV
if(hX
w1(393,a5"A[A>=VarBegin&&data->ByteCode.size()>0]"
,m1"cDup"
,aL(A)q41(B)wE);q3
Lfi;}
oP
gE
A)){B
gV
if(B
g3
1){C=qS
dU
C
oL
D
qV
D==B
a8(394,"D[D==B] C[C==A] B[B>=VarBegin&&data->ByteCode.size()>1] A[IsUnaryOpcode(A)]"
,"D C cDup"
,aL(A)q41(B)<<", "
aR(C)<<", D "
w3(D)wE);q3
Lfj;}
}
}
}
}
q3
Lfk;Laa:dO
dT;Lab:qE=d2;g7
Lac:dG
4));gY
Lfl:gJ
d6;Lfm:o5
Lfn:q3
TailCall_cMul;Lad:gA
dG
4));hU
Lfl;Lae:qE=x+qA(1);gY
Lbo:gJ
d6;q3
Lfn;Laf:dP
cSub;Lfo:q3
hE;Lag:gL
dZ
Lfp:o5
Lfq:q3
oA;Lah:gL
g2
q4
Lga:d1
Lgb:qF
cRSub);g7
Lai:hJ
gS
o1
dZ
q3
Lga;Laj:gL
dZ
q3
Lgb;Lak:gL
hI
q4
Lgc:d1
Lgd:qF
B);Lge:gJ
cSub;qQ
Lfo;Lal:hJ
q0
d3
Lgc;Lam:gL
g2
q4
q3
Lgd;Lan:qR
y+x;Lao:qT
Lbl:hF
q4
g7
Lap:qT
g2
o9
oT
hU
Lga;Laq:q7
oD
Lga;Lba:qR
fp_and(x
gH
Lbb:dG
0));q0[0]o1
qF
d6);dG
1));Lgf:oB
Lgg:gJ
oI;q3
Lfp;Lbc:hJ
qS
hA
gF
Lgh:q3
o0;Lbd:qR
y/x;q3
oJ
Lbe:qR
fp_equal(y
h6
Lbf:qS
hA
gF
Lgi:q3
dV;Lbg:qT
hF
q4
Lgj:gJ
cNot;o5
Lgk:q3
TailCall_cNot;Lbh:qT
dZ
Lgl:gJ
d9;o5
Lgm:q3
h3;Lbi:qT
gK
Lgl;Lbj:qR
fp_less(x
gH
Lbk:qR
fp_lessOrEq(x
gH
Lbm:oG
cRSqrt);g7
Lbn:qE=qA(1)/x;g7
Lbp:qT
dZ
q3
Lgj;Lbq:qR
fp_less(y
h6
Lca:qR
fp_lessOrEq(y
h6
Lcb:qR
fp_max(x
gH
Lcc:qR
fp_min(x
gH
Lcd:qR
fp_mod(y
h6
Lce:dP
cSqr;Lgn:q3
TailCall_cSqr;Lcf:dP
cDiv;q3
Lgh;Lcg:g2
q1
cSqr);qF
d6);Lgo:gJ
cNeg;qQ
hD;Lch:q7
q1
cSqr
gI
Lgo;Lci:qE=x+qA(1);gS
o1
q7
q1
cPow);g7
Lcj:gY
q3
Lfn;Lck:qR
x;Lgp:qT
dZ
q3
Lfm;Lcl:q7
q6
Lgq:hI
q4
Lha:qF
A);oT
Lhb:hU
Lfm;Lcm:qT
q3
Lgq;Lcn:qT
hI
q1
B
gI
Lha;Lco:qT
g2
q4
q3
Lha;Lcp:qS
o1
q3
Lbl;Lcq:qS
hA
gF
q3
Lfn;Lda:qE=x+x;o7
Ldb:qR
x;dK=q5
oR
gA
qF
A);oU);oB
mV
Lgg;Ldc:qR
x
oR
gU
oU
gI
Lgf;Ldd:qT
gA
qB
x+x
gI
Lhb;Lde:q7
hY
g7
Ldf:qC1;q3
Lgp;Ldg:hJ
q3
Lcq;Ldh:qR
x;dK=q5
oR
gA
qF
A);oU);oB
mV
Lge;Ldi:qC1;q3
oJ
Ldj:q0[0]=dY;q2-=1
oR
Lhc:gJ
oI;q3
Lfq;Ldk:qT
gK
Lgo;Ldl:dZ
Lhd:qF
cSqr
gI
Lfm;Ldm:g2
q4
q3
Lhd;Ldn:qR
fp_nequal(y
h6
Ldo:qS
hA
gF
Lhe:q3
TailCall_cNEqual;Ldp:hJ
dO
oN
Ldq:hJ
g7
Lea:dO
Lgk;Leb:oG
cAbsNotNot);g7
Lec:hF
q4
Lem:qF
cAbsNot);g7
Led:qE=x;Lej:dP
cEqual;q3
Lgi;Lee:dP
o8;q3
Lhe;Lef:dP
hC;q3
TailCall_cLessOrEq;Leg:dP
cLess;q3
TailCall_cLess;Leh:dP
h5;q3
TailCall_cGreaterOrEq;Lei:dP
hS;q3
TailCall_cGreater;Lek:dP
d9;q3
Lgm;Lel:qE=fp_not(mX
Len:qE=x;q3
Lee;Leo:qR
fp_or(x
gH
Lep:qT
hF
q4
gJ
cInv;qQ
TailCall_cInv;Leq:dO
Lgn;Lfa:dG
0));q0[0]o1
q3
Lfl;Lfb:dO
Lhc;Lfc:qR
y-x;q3
oJ
Lfd:hJ
q3
Lhc;Lfe:qT
g2
o9
d1
oT
hU
Lgb;Lff:q7
o9
qF
cSub
gI
Lgb;Lfg:qR
x-y
oR
q7
o9
g7
Lfh:hJ
qS=q5
qP
q1
OppositeComparisonOpcode(A));g7
Lfi:qM
dY);g7
Lfj:q0[0]=dY;g7
Lfk:qM
dW);g7
g7
q3
TailCall_cAnd;q3
TailCall_cMax;q3
TailCall_cMin;q3
TailCall_cMod;q3
hD;q3
h3;q3
TailCall_cOr;q3
TailCall_cRDiv;q3
hE;
#endif
#if(FP_FLOAT_VERSION)
qA
x;hB
A;qA
y;hB
B;hB
C;hB
D;hG
dW){dT:gC
h9
qD
mN(236,mF" "
mB,mB,);q3
Laa;qW
w1(40,"x "
mB,"[fp_abs(x)]"
,w9);q3
Lab;gT
qG
w1(295,wB
mB,"A"
,aL(A)wE);o3
TailCall_cAcos:gC
cAcos:g5>=qA(-1)&&x<=h8
w1(44,"x[x>=Value_t(-1)&&x<=Value_t(1)] cAcos"
,"[fp_acos(x)]"
,w9);q3
Lac;qK
TailCall_cAcosh:gC
cAcosh:g5>=h8
w1(41,"x[x>=Value_t(1)] cAcosh"
,"[fp_acosh(x)]"
,w9);q3
Lad;qK
oA:gC
oI:qD
h4
gW
aS(186,wP
mQ
aZ,"[Value_t(4)]"
mD,);q3
Lae;qJ
g9
2]==oI){qH-3]aS(187,aZ
wF
aZ,w7" [Value_t(4)]"
mD,);q3
Laf;}
}
gQ
q3
dC;gC
dL
hR
aS(189,wP"x"
wF
wJ,"[x+Value_t(1)]"
mD,w9);q3
Lag;}
}
q3
dC;gC
mN(243,mF" "
wJ,qB1,);q3
Lah;qW
gW
qL
w1(180,mG
mQ"x "
wJ,"[y+x] "
wJ,q31);q3
Lai;qJ
cRSub:g1
gX
3]qL
w1(121,mG
mQ
mW,mI
mQ
wY,q31);q3
Laj;qJ
mN(122,mF" "
mW,"[-x] "
mQ
wY,w9);q3
Lak;gC
dJ
w1(120,mG
mW,mI
wY,q31);q3
Lal;qJ
o4
hV
hG
dR
gX
4]qL
w1(115,mG
mQ
wL,mI
mQ
a9,qD1(B)<<","
m7);q3
Lam;qJ
mN(116,mF" "
wL,"[-x] "
mQ
a9,qD1(B)wE);q3
Lan;gC
dJ
w1(114,mG
wL,mI
a9,qD1(B)<<","
m7);q3
oJ}
dI
w1(76,qA1
wJ,"[y+x]"
,q31);q3
Lap;}
hN
w1(75,w8
wJ,,w9);q3
oM}
d0
g4
dC:;A
gV
hO
w1(113,"x "
wY" "
wA
wJ,"[DO_STACKPLUS1] A "
wU
mQ
wY,aL(A)<<","
mH);hM
Lba;}
w1(118,wY" "
wA
wJ,"[DO_STACKPLUS1] A "
mQ
wY,aL(A)wE);hM
Lbb;}
qK
TailCall_cAnd:gC
cAnd:qH
0]qC
wW(169,mG"x cAnd"
,"[fp_and(x,y)]"
,q31);q3
Lbc;qK
TailCall_cAsin:gC
cAsin:g5>=qA(-1)&&x<=h8
w1(45,"x[x>=Value_t(-1)&&x<=Value_t(1)] cAsin"
,"[fp_asin(x)]"
,w9);q3
Lbd;qK
TailCall_cAsinh:gC
cAsinh:qH
0]qC
w1(42,"x cAsinh"
,"[fp_asinh(x)]"
,w9);q3
Lbe;}
qN
TailCall_cAtan:gC
cAtan:qH
0]qC
w1(46,"x cAtan"
,"[fp_atan(x)]"
,w9);q3
Lbf;}
qN
TailCall_cAtan2:gC
cAtan2:qH
0]qC
wW(83,mG"x cAtan2"
,"[fp_atan2(y,x)]"
,q31);q3
Lbg;qK
TailCall_cAtanh:gC
cAtanh:g5>qA(-1)&&x<h8
w1(43,"x[x>Value_t(-1)&&x<Value_t(1)] cAtanh"
,"[fp_atanh(x)]"
,w9);q3
Lbh;qK
TailCall_cCbrt:gC
cCbrt:qH
0]qC
w1(47,"x cCbrt"
,"[fp_cbrt(x)]"
,w9);q3
Lbi;}
qN
TailCall_cCeil:gC
cCeil:qD
mN(304,mF" "
a6,aD
aK,);q3
Lbj;qW
w1(48,"x "
a6,"[fp_ceil(x)]"
,w9);q3
Lbk;gT
aP(298,aM
a6,"A"
,aL(A)wE);o3
TailCall_cCos:gC
cCos:qD
h9
w1(339,mB" "
mC,mC,);q3
Lbl;gC
mN(341,mF" "
mC,mC,);q3
Lbl;qW
w1(49,"x "
mC,"[fp_cos(x)]"
,w9);q3
Lbm;}
qN
TailCall_cCosh:gC
cCosh:qD
h9
w1(340,mB" "
mA,mA,);q3
Lbn;gC
cAcosh:w1(232,"cAcosh "
mA,,);q3
oN
gC
cAsinh:w1(353,"cAsinh "
mA,"[DO_STACKPLUS1] "
wX" [Value_t(1)] "
mQ
mU,);hM
Lbp;gC
mN(342,mF" "
mA,mA,);q3
Lbn;qW
w1(50,"x "
mA,"[fp_cosh(x)]"
,w9);q3
Lbq;}
qN
TailCall_cDeg:gC
cDeg:qH
0]qC
w1(65,"x cDeg"
,"[RadiansToDegrees(x)]"
,w9);q3
Lca;}
qN
o0:gC
cDiv:qD
cCos:w1(356,mC
aG,aT
mD,);q3
Lcb;gC
cCot:w1(360,aU
aG,aV
mD,);q3
Lcc;gC
cCsc:w1(358,aW
aG,aX
mD,);q3
Lcd;gC
h4
w1(159,wP
mY,"[Value_t(0)]"
wF"[Value_t(1)] "
wJ,);q3
Lce;gC
aY(310,mT
mY,mF" "
aC
mD,);q3
Lcf;gC
dA:w1(311,m3
aG,mF" "
m3
mD,);q3
Lcg;aE
w1(241,aA
aG,w7,);q3
Lch;gC
d7
w1(309,"cPow"
aG,mF
wV
mD,);q3
Lci;gC
cSec:w1(359,aT
aG,mC
mD,);o7
gC
cSin:w1(355,aX
aG,aW
mD,);q3
Lck;gC
cTan:w1(357,aV
aG,aU
mD,);q3
Lcl;qW
g6
1)a8(72,wG
mY,,w9);q3
oM
oP
x!=gN
qI
g9
2]qL
if((y/x)==gO
w1(198,"y[(y/x)==GetRadiansToDegreesFactor<Value_t>()]"
mM,"cDeg"
,q31);q3
oO(y/x)==gP
w1(199,"y[(y/x)==GetDegreesToRadiansFactor<Value_t>()]"
mM,"cRad"
,q31);q3
Lcn;}
w1(200,"y"
mM,"[y/x]"
mD,q31);q3
Lco;qJ
mN(177,mF" "
wO
mY,"[-x]"
aG,w9);q3
Lcp;gC
dJ
w1(73,mG
wO
mY,"[y/x]"
,q31);q3
Lcq;}
w1(202,wO
mY,"[Value_t(1)/x]"
mD,w9);q3
Lda;}
d0
gT
h1
qI
cDiv:hV
w1(94,q51" "
wA
mY,"[DO_STACKPLUS1] "
m1"A"
wF
mY,aL(A)q41(B)wE);hM
Ldb;qJ
oC
hG
gS){qW
w1(89,"x "
a7" "
wA
mY,"A"
wF
wU
a7,aL(A)<<","
mH);q3
Ldc;g4
hV
w1(88,"B[B>=VarBegin] "
a7" "
wA
mY,"A"
wF
m1
a7,aL(A)q41(B)wE);q3
Ldd;}
}
gQ
qK
dV:gC
d8
g5==gN
q81(255,mB" "
w8
m0,wU
m0,w9);q3
Lde;gC
hH
w1(257,wX" "
w8
m0,wU
m0,w9);q3
Lde;}
}
wW(167,qA1
m0,"[fp_equal(y,x)]"
,q31);q3
Ldf;qK
TailCall_cExp:gC
cExp:qD
gX
1]qC
w1(306,"x "
mQ
aC,mT"[fp_exp(x)]"
mD,w9);q3
Ldg;qJ
cLog:A
a1(222,wB
mP" "
aC,"A"
,aL(A)wE);q3
oN
qJ
oE
w1(51,"x "
aC,"[fp_exp(x)]"
,w9);q3
Ldh;}
qN
TailCall_cExp2:gC
dA:qD
gX
1]qC
w1(307,"x "
mQ
m3,m3" [fp_exp2(x)]"
mD,w9);q3
Ldi;qJ
oZ:A
a1(223,wB
m4" "
m3,"A"
,aL(A)wE);q3
oN
qJ
oE
w1(52,"x "
m3,"[fp_exp2(x)]"
,w9);q3
Ldj;}
w1(399,m3,"[DO_STACKPLUS1] [fp_log(Value_t(2))]"
wF
aC,);hM
Ldk;TailCall_cFloor:gC
cFloor:qD
mN(303,mF" "
aD,a6
aK,);q3
Ldl;qW
w1(53,"x "
aD,"[fp_floor(x)]"
,w9);q3
Ldm;gT
aP(297,aM
aD,"A"
,aL(A)wE);o3
TailCall_cGreater:gC
hS:qH
0]qC
wW(165,qA1
mO,"[fp_less(x,y)]"
,q31);q3
Ldn;}
g6-hT
w1(333,"x[x==Value_t(-0.5)] "
mO,mF" "
mL,w9);q3
Ldo;qK
TailCall_cGreaterOrEq:gC
h5:g5!=gN
hP==oW
w1(329,mB" "
wO
m2,"[Value_t(0.5)/x]"
wF
mJ,w9);q3
Ldp;}
}
wW(166,qA1
m2,"[fp_lessOrEq(x,y)]"
,q31);q3
Ldq;}
g6
hT
w1(332,"x[x==Value_t(0.5)] "
m2,"cAbsNotNot"
,w9);q3
Lea;qK
TailCall_cInt:gC
cInt:qD
oE
w1(54,"x cInt"
,"[fp_int(x)]"
,w9);q3
Leb;gT
aP(299,aM"cInt"
,"A"
,aL(A)wE);o3
TailCall_cInv:aE
qD
cCos:w1(362,mC" "
aA,aT,);q3
Lec;gC
cCot:w1(366,aU" "
aA,aV,);q3
Led;gC
cCsc:w1(364,aW" "
aA,aX,);q3
Lee;aE
w1(237,aA" "
aA,,);q3
oN
gC
d7
w1(239,"cPow "
aA,mF
wV,);q3
Lef;gC
cSec:w1(365,aT" "
aA,mC,);q3
Leg;gC
cSin:w1(361,aX" "
aA,aW,);q3
Leh;gC
oY
w1(67,mU" "
aA,"cRSqrt"
,);q3
Lei;gC
cTan:w1(363,aV" "
aA,aU,);q3
Lej;qW
if(x!=gN
w1(69,wO
aA,"[Value_t(1)/x]"
,w9);q3
Lek;}
gQ
qN
TailCall_cLess:gC
o6
g5==gN
A
a1(124,wB
w8
a4,m5,q71(A)wE);q3
Lel;}
oP
x!=gN
hP==oW
w1(328,mB" "
wO
a4,"[Value_t(0.5)/x]"
wF"cNot"
,w9);q3
Lem;}
}
wW(163,qA1
a4,"[fp_less(y,x)]"
,q31);q3
Len;}
g6
hT
w1(331,"x[x==Value_t(0.5)] "
a4,mL,w9);q3
Leo;qK
TailCall_cLessOrEq:gC
hC:qH
0]qC
wW(164,qA1
mK,"[fp_lessOrEq(y,x)]"
,q31);q3
Lep;}
g6-hT
w1(334,"x[x==Value_t(-0.5)] "
mK,mF" cAbsNotNot"
,w9);q3
Leq;qK
TailCall_cLog:gC
cLog:qD
aY(225,mT
mP,,);q3
oN
gM
w1(411,wK
wF
mP,mP" [fp_log(x)] "
wJ,w9);q3
Lfa;}
aI(142,wX" "
mP,mB" "
mP" "
aZ,);q3
Lfb;mR(55,wK" "
mP,"[fp_log(x)]"
,w9);q3
Lfc;}
gQ
qN
TailCall_cLog10:gC
w0:qD
aY(401,mT
m8,"[DO_STACKPLUS1] [fp_log10(fp_const_e<Value_t>())]"
mD,);hM
Lfd;gM
w1(412,wK
wF
m8,m8" [fp_log10(x)] "
wJ,w9);q3
Lfe;}
aI(144,wX" "
m8,mB" "
m8" "
aZ,);q3
Lff;mR(56,wK" "
m8,"[fp_log10(x)]"
,w9);q3
Lfg;}
gQ
qN
TailCall_cLog2:gC
oZ:qD
aY(400,mT
m4,"[DO_STACKPLUS1] [fp_log2(fp_const_e<Value_t>())]"
mD,);hM
Lfh;gC
dA:w1(226,m3" "
m4,,);q3
oN
gM
w1(410,wK
wF
m4,m4" [fp_log2(x)] "
wJ,w9);q3
Lfi;}
aI(143,wX" "
m4,mB" "
m4" "
aZ,);q3
Lfj;mR(57,wK" "
m4,"[fp_log2(x)]"
,w9);q3
Lfk;}
gQ
qN
TailCall_cMax:gC
cMax:aB(149,wP
mZ,,);q3
oN
qW
wW(82,qA1
mZ,"[fp_max(x,y)]"
,q31);q3
Lfl;}
d0
gT
h1
qI
h4
aQ(151,a5
wP
wA
mZ,m1"cDup"
,aL(A)q41(B)wE);q3
oN
qJ
cMax:aQ(153,a5
mZ" "
wA
mZ,m1
mZ,aL(A)q41(B)wE);q3
oN}
gQ
qK
TailCall_cMin:gC
cMin:aB(148,wP
a0,,);q3
oN
qW
wW(81,qA1
a0,"[fp_min(x,y)]"
,q31);q3
Lfm;}
d0
gT
h1
qI
h4
aQ(150,a5
wP
wA
a0,m1"cDup"
,aL(A)q41(B)wE);q3
oN
qJ
cMin:aQ(152,a5
a0" "
wA
a0,m1
a0,aL(A)q41(B)wE);q3
oN}
gQ
qK
TailCall_cMod:gC
cMod:g5!=gN
wW(74,mG
wO"cMod"
,"[fp_mod(y,x)]"
,q31);q3
Lfn;}
qK
TailCall_cMul:gC
d6:aB(396,wP
w7,wX,);q3
Lfo;aE
w1(242,aA
mD,mY,);q3
Lfp;gC
g8
A=qS;h1
g1
d6:B=dS
hX
w1(388,wQ
wF
wA
mF
mD,m1
wX
wF
mF,aL(A)q41(B)wE);q3
Lfq;}
q3
Default2;g4
Default2:;aQ(382,a5
wA
mF
mD,m1
wX
aK,aL(A)q41(B)wE);q3
Lga;}
}
}
q3
dD;gC
d7
hP
qC
hR
aS(190,wP"x"
wV
mD,"[x+Value_t(1)]"
wV,w9);q3
Lgb;}
}
q3
dD;qW
hN
qI
d6:A
qV
A
qY
w1(133,wA
w7" "
w8
w7,wU
w7,q71(A)wE);q3
Lgc;}
q3
Default4;g4
Default4:;A=qS
dU
IsBinaryOpcode(A)g0
A)){g1
dJ
w1(132,mG
w5,wU
w7,q71(A)<<","
m7);q3
Lgd;g4
hL
IsBinaryOpcode(B)g0
B)){hG
dR
dJ
w1(136,mG
wC,m5,q71(A)q41(B)<<","
m7);q3
Lge;g4
C=dS
C
qY
w1(134,"C[C>=VarBegin] "
wC,m5,q71(A)q41(B)<<", "
aR(C)wE);q3
Lgf;oP
gE
C)g0
C)a8(135,"C[IsUnaryOpcode(C)&&!HasInvalidRangesOpcode(C)] "
wC,m1
m5,q71(A)q41(B)<<", "
aR(C)wE);q3
Lgg;}
}
oP
B
qY
w1(130,"B[B>=VarBegin] "
w5,wU
w7,q71(A)q41(B)wE);q3
Lgc;oP
gE
B)g0
B)a8(131,"B[IsUnaryOpcode(B)&&!HasInvalidRangesOpcode(B)] "
w5,m5,q71(A)q41(B)wE);q3
Lgh;}
}
}
h1
w1(128,wA
w8
w7,"[x]"
,q71(A)wE);q3
Lgi;oP
gE
A)g0
A)a8(129,"A[IsUnaryOpcode(A)&&!HasInvalidRangesOpcode(A)] "
w8
w7,wU
w7,q71(A)wE);q3
Lgj;}
}
}
qI
oI:g1
h4
if(x+x
q01(193,"cDup[x+x==Value_t(1)] "
wJ
wT,,w9);q3
Lgk;}
w1(194,aZ
wT,"[x+x]"
mD,w9);q3
Lgl;gC
g9
3]qL
A=dK;h1
w1(282,wA"y"
wF
wJ
wT,q11"A "
mS
wF
wJ,wM", "
mG"= "
<<y<<","
mE(A)wE);q3
Lgm;}
dI
w1(281,mG
wJ
wT,q11
mS" "
wJ,q31);q3
Lgn;qJ
cDeg:w1(145,"cDeg"
wT,"[RadiansToDegrees(x)]"
mD,w9);q3
Lgo;gC
cDiv:hV
hG
dR
g9
4]qL
w1(101,"y"
wF
q51
wT,mS
wF
m1
mY,qD1(B)<<","
m7);q3
Lgp;qJ
mN(102,mF" B[B>=VarBegin]"
aG
wT,m9
m1
mY,qD1(B)wE);q3
Lgq;gC
dJ
w1(100,mG
q51
wT,mS" "
m1
mY,qD1(B)<<","
m7);q3
Lha;}
qJ
d6:g1
gX
3]==dY){if(x+x
q01(195,"cDup[x+x==Value_t(1)] "
wJ
qE1,w7,w9);q3
Lhb;}
w1(196,aZ
qE1,w7" [x+x]"
mD,w9);q3
Lhc;dI
if((y*x)==gO
w1(182,"y[(y*x)==GetRadiansToDegreesFactor<Value_t>()]"
qE1,"cDeg"
,q31);q3
oO(y*x)==gP
w1(183,"y[(y*x)==GetDegreesToRadiansFactor<Value_t>()]"
qE1,"cRad"
,q31);q3
Lcn;oP
y*x
q01(184,"y[y*x==Value_t(1)]"
qE1,,q31);q3
Lhd;}
w1(185,"y"
qE1,mS
mD,q31);q3
Lhe;qJ
mN(174,mF
wT,"[-x]"
mD,w9);q3
Lhf;gC
oC
g1
g9
3]qL
w1(108,"y"
wF
a3,mS
wF
a7,q31);q3
Lhg;qJ
mN(109,mF" "
a3,m9
a7,w9);q3
Lhh;gC
dJ
w1(107,mG
a3,mS" "
a7,q31);q3
Lhi;qJ
cRad:w1(146,"cRad"
wT,"[DegreesToRadians(x)]"
mD,w9);q3
Lhj;gC
o4
hR==d6){qH-3]qL
A=dK;h1
w1(283,wA"y"
wF
qB1
wT,q11"A "
mS
wF
qB1,wM", "
mG"= "
<<y<<","
mE(A)wE);q3
Lhk;}
}
dI
w1(71,"y"
wT,mS,q31);q3
Lhl;}
g6
1)a8(70,wG
w7,,w9);q3
oM}
g6
2)a8(139,"x[x==Value_t(2)]"
mD,aZ,w9);q3
Lhm;oP
x==gO
w1(140,"x[x==GetRadiansToDegreesFactor<Value_t>()]"
mD,"cDeg"
,w9);q3
Lhn;oP
x==gP
w1(141,"x[x==GetDegreesToRadiansFactor<Value_t>()]"
mD,"cRad"
,w9);q3
Lho;}
g6-1)a8(176,"x[x==Value_t(-1)]"
mD,mF,w9);q3
Lhp;}
d0
g4
dD:;A
gV
h1
qI
cDiv:hV
w1(97,q51
aJ,"[DO_STACKPLUS1] A"
wF
m1
mY,aL(A)q41(B)wE);hM
Lhq;}
q3
hK
d6:g1
g8
B=dS
hX
w1(385,a5
mF
wF
wA
w7,m1
wX
wF
mF,aL(A)q41(B)wE);q3
Lfq;}
q3
dE;g4
dE:;aQ(376,wQ
wF
wA
w7,m1
wX
mD,aL(A)q41(B)wE);q3
Lia;}
}
q3
hK
g8
aQ(379,a5
mF
aJ,m1
wX
aK,aL(A)q41(B)wE);q3
Lga;}
q3
hK
oC
hR
qC
w1(90,"x "
a7
aJ,"[DO_STACKPLUS1] A "
q11
a7,aL(A)<<","
mH);hM
Lib;}
w1(104,a7
aJ,"[DO_STACKPLUS1] A"
wF
a7,aL(A)wE);hM
Lic;g4
oK:;B=qS
dU
hX
w1(373,a5
wA
w7,m1
wX,aL(A)q41(B)wE);q3
Lfo;}
}
oP
gE
A)){B=qS
dU
B
g3
1){hR==d6){C=dS
C
oL
D=dK
dU
D==B
a8(395,"D[D==B] C[C==A]"
wF"B[B>=VarBegin&&data->ByteCode.size()>1] A[IsUnaryOpcode(A)]"
mD,"D C "
wX
mD,aL(A)q41(B)<<", "
aR(C)<<", D "
w3(D)wE);q3
Lid;}
}
}
}
qK
TailCall_cNEqual:gC
o8:g5==gN
q81(256,mB" "
w8
wR,wU
wR,w9);q3
Lie;gC
hH
w1(258,wX" "
w8
wR,wU
wR,w9);q3
Lie;}
}
wW(168,qA1
wR,"[fp_nequal(y,x)]"
,q31);q3
Lif;qK
hD:gC
g8
qD
dL
w1(175,"x"
wF
mF,"[-x]"
mD,w9);q3
Lig;qJ
mN(238,mF
aK,,);q3
oN
gC
cSin:wZ(347,"x"
wF
aX
aK,m9
aX,w9);q3
Lih;}
qJ
oV:wZ(348,"x"
wF
aN
aK,m9
aN,w9);q3
Lii;}
qJ
cTan:wZ(349,"x"
wF
aV
aK,m9
aV,w9);q3
Lij;}
qJ
oX:wZ(350,"x"
wF"cTanh"
aK,m9"cTanh"
,w9);q3
Lik;}
qJ
oE
w1(68,"x"
aK,"[-x]"
,w9);q3
Lil;}
qN
TailCall_cNot:gC
cNot:qD
h9
w1(286,mB
m6,"cNot"
,);q3
Lim;gC
cAbsNot:A=qS
dU
gG
w1(291,"A[IsLogicalOpcode(A)] "
mL
m6,"A"
,aL(A)wE);q3
oN
oP
A!=q5
a8(292,"A[A!=cImmed] "
mL
m6,"A cAbsNotNot"
,aL(A)wE);q3
Lin;}
q3
dF;gC
cAbsNotNot:w1(289,"cAbsNotNot"
m6,mL,);q3
Lio;gC
d8
w1(252,m0
m6,wR,);q3
Lip;gC
hS:w1(250,mO
m6,mK,);q3
Liq;gC
h5:w1(251,m2
m6,a4,);q3
Lja;gC
o6
w1(248,a4
m6,m2,);q3
Ljb;gC
hC:w1(249,mK
m6,mO,);q3
Ljc;gC
o8:w1(253,wR
m6,m0,);q3
Ljd;gC
mN(285,mF
m6,"cNot"
,);q3
Lim;gC
cNot:w1(287,"cNot"
m6,mJ,);q3
Lje;gC
d9:w1(288,mJ
m6,"cNot"
,);q3
Lim;qW
w1(85,"x"
m6,"[fp_not(x)]"
,w9);q3
Ljf;g4
dF:;A
gV
qG
w1(293,wB"cNot"
,"A "
mL,aL(A)wE);q3
Ljg;qK
TailCall_cOr:gC
cOr:qH
0]qC
wW(170,mG"x cOr"
,"[fp_or(x,y)]"
,q31);q3
Ljh;qK
TailCall_cPow:gC
d7
qH
0]qC
if(!gR
x+x)){hP==cSqr
a8(14,wX" x[!isEvenInteger(x+x)]"
wV,mB" [x+x]"
wV,w9);q3
Lji;}
oP
IsIntegerConst(x)){qI
aY(35,mT
wH,q11
aC,w9);q3
Ljj;gC
dA:w1(36,m3" "
wH,q11
m3,w9);q3
Ljk;gC
d7
hR
qL
if(!IsIntegerConst(y)a8(34,"y[!IsIntegerConst(y)]"
wV" "
wH,mS
wV,q31);q3
Ljl;}
}
w1(37,"cPow "
wH,q11"cPow"
,w9);q3
Ljm;}
oP
gR
x)){q81(336,mB" x[isEvenInteger(x)]"
wV,wU"cPow"
,w9);q3
Ljn;gC
g9
2]==oW
w1(337,mB
wF"x[isEvenInteger(x)]"
wV,w7" "
wU"cPow"
,w9);q3
Ljo;}
gQ}
hN
w1(161,w8"cPow"
,"[Value_t(0)]"
wF"[Value_t(1)] "
wJ,w9);q3
Ljp;}
g6
hT
w1(214,"x[x==Value_t(0.5)]"
wV,mU,w9);q3
Ljq;}
g6
1)/qA(3)a8(215,"x[x==Value_t(1)/Value_t(3)]"
wV,"cCbrt"
,w9);q3
Lka;}
g6
1)/qA(-3)a8(216,"x[x==Value_t(1)/Value_t(-3)]"
wV,"cCbrt "
aA,w9);q3
Lkb;}
g6-hT
w1(217,"x[x==Value_t(-0.5)]"
wV,"cRSqrt"
,w9);q3
Lkc;}
g6-1)a8(218,"x[x==Value_t(-1)]"
wV,aA,w9);q3
Lkd;}
qI
d7
hR
qL
if(gR
y)&&!gR
x*y)a8(13,"y[isEvenInteger(y)&&!isEvenInteger(x*y)]"
wV" x"
wV,mB" "
mS
wV,q31);q3
Lke;}
w1(212,"y"
wV" x"
wV,mS
wV,q31);q3
Ljl;aI(38,wX" x"
wV,"[x+x]"
wV,w9);q3
Lkf;gC
dJ
if(y!=qA(0)||x>=gN
w1(84,"y[y!=Value_t(0)||x>=Value_t(0)] x"
wV,"[fp_pow(y,x)]"
,q31);q3
Lkg;}
gQ
w1(370,"x"
wV,"[DO_POWI]"
,w9)dU
TryCompilePowi(x))g7}
qN
TailCall_cRDiv:gC
oC
h7
w1(91,wG
a7,aA,w9);q3
Lkd;qK
TailCall_cRad:gC
cRad:qH
0]qC
w1(66,"x cRad"
,"[DegreesToRadians(x)]"
,w9);q3
Lkh;}
qN
dN:gC
cSin:qD
mN(343,mF" "
aX,aX
aK,);q3
Lki;qW
w1(58,"x "
aX,"[fp_sin(x)]"
,w9);q3
Lkj;}
qN
TailCall_cSinh:gC
oV:qD
cAcosh:w1(352,"cAcosh "
aN,"[DO_STACKPLUS1] "
wX" [Value_t(-1)] "
mQ
mU,);hM
Lkk;gC
cAsinh:w1(231,"cAsinh "
aN,,);q3
oN
gC
mN(344,mF" "
aN,aN
aK,);q3
Lkl;qW
w1(59,"x "
aN,"[fp_sinh(x)]"
,w9);q3
Lkm;}
qN
TailCall_cSqr:gC
hH
qD
h9
w1(391,mB" "
wX,wX,);q3
Lkn;gC
mN(390,mF" "
wX,wX,);q3
Lkn;gC
oY
A
a1(220,wB
mU" "
wX,"A"
,aL(A)wE);q3
oN}
gQ
qN
TailCall_cSqrt:gC
oY
qD
hH
w1(15,wX" "
mU,mB,);q3
Lko;qW
if(x>=gN
w1(60,"x[x>=Value_t(0)] "
mU,"[fp_sqrt(x)]"
,w9);q3
Lkp;}
gQ
qN
hE:gC
o4
aB(191,wP
qB1,"[Value_t(0)]"
mD,);q3
Lkq;gC
mN(244,mF
aO,wJ,);q3
Lla;qW
hN
w1(77,w8
qB1,,w9);q3
oM}
wW(78,mG"x"
aO,"[y-x]"
,q31);q3
Llb;}
w1(207,"x"
aO,"[-x] "
wJ,w9);q3
Llc;gT
hO
w1(112,"x "
wY" "
wA
qB1,"A "
mQ
wU
wY,aL(A)<<","
mH);q3
Lld;}
w1(119,wY" "
wA
qB1,"[DO_STACKPLUS1] A"
aO" "
wY,aL(A)wE);hM
Lle;}
qK
dQ:gC
cTan:qD
cAtan2:w1(235,"cAtan2 "
aV,mY,);q3
Lfp;gC
mN(345,mF" "
aV,aV
aK,);q3
Llf;qW
w1(62,"x "
aV,"[fp_tan(x)]"
,w9);q3
Llg;}
qN
TailCall_cTanh:gC
oX:qD
mN(346,mF" cTanh"
,"cTanh"
aK,);q3
Llh;qW
w1(63,"x cTanh"
,"[fp_tanh(x)]"
,w9);q3
Lli;}
qN
TailCall_cTrunc:gC
cTrunc:qD
oE
w1(64,"x cTrunc"
,"[fp_trunc(x)]"
,w9);q3
Llj;gT
aP(296,aM"cTrunc"
,"A"
,aL(A)wE);o3
g4
Default0:;A=dW
dU
IsComparisonOpcode(A)){qH
0]qC
gW
qL
w1(260,mG
mQ
w6,"[x-y] A"
,aL(A)<<q61);q3
Llk;qJ
cAtan:if(d2<fp_const_pi<qA>()*qA(hT
w1(276,"cAtan[fp_abs(x)<fp_const_pi<Value_t>()*Value_t(0.5)]"
aH,"[fp_tan(x)] A"
,aL(A)<<","
mH);q3
Lll;qJ
cExp:q21(266,"cExp[x>Value_t(0)]"
aH,"[fp_log(x)] A"
,aL(A)<<","
mH);q3
Llm;qJ
dA:q21(267,"cExp2[x>Value_t(0)]"
aH,"[fp_log2(x)] A"
,aL(A)<<","
mH);q3
Lln;qJ
cLog:qU
w1(269,wI
mP
aH,m1"[fp_exp(x)] A"
,aL(A)<<q91(B)wE);q3
Llo;qJ
w0:qU
w1(271,wI
m8
aH,m1"[fp_pow(Value_t(10),x)] A"
,aL(A)<<q91(B)wE);q3
Llp;qJ
oZ:qU
w1(270,wI
m4
aH,m1"[fp_exp2(x)] A"
,aL(A)<<q91(B)wE);q3
Llq;qJ
g9
2]qL
if(y>gN
w1(262,"y[y>Value_t(0)]"
wF
w6,"[x/y] A"
,aL(A)<<q61);q3
Lma;oP
y<gN
w1(263,"y[y<Value_t(0)]"
wF
w6,"[x/y] {OppositeComparisonOpcode(A)}"
,aL(A)<<q61);q3
Lmb;}
qJ
mN(261,mF
aH,"[-x] {OppositeComparisonOpcode(A)}"
,aL(A)<<","
mH);q3
Lmc;gC
d7
if(x>gN
hR
qL
if(y>gN
w1(264,"y[y>Value_t(0)] cPow[x>Value_t(0)]"
aH,"[fp_pow(x,1/y)] A"
,aL(A)<<q61);q3
Lmd;}
}
qJ
oV:w1(277,aN
aH,"[fp_asinh(x)] A"
,aL(A)<<","
mH);q3
Lme;gC
hH
q21(265,"cSqr[x>Value_t(0)]"
aH,mB" [fp_sqrt(x)] A"
,aL(A)<<","
mH);q3
Lmf;qJ
oX:if(d2<h8
w1(278,"cTanh[fp_abs(x)<Value_t(1)]"
aH,"[fp_atanh(x)] A"
,aL(A)<<","
mH);q3
Lmg;}
gQ}
oP
A
g3
0){B
gV
if(hX
w1(393,a5"A[A>=VarBegin&&data->ByteCode.size()>0]"
,m1"cDup"
,aL(A)q41(B)wE);q3
Lmh;}
oP
gE
A)){B
gV
if(B
g3
1){C=qS
dU
C
oL
D
qV
D==B
a8(394,"D[D==B] C[C==A] B[B>=VarBegin&&data->ByteCode.size()>1] A[IsUnaryOpcode(A)]"
,"D C cDup"
,aL(A)q41(B)<<", "
aR(C)<<", D "
w3(D)wE);q3
Lmi;}
}
}
}
}
q3
Lmj;Laa:q0
gF
Lmk:q3
dT;Lab:qE=d2;g7
Lac:qE=fp_acos(mX
Lad:qE=fp_acosh(mX
Lae:dG
4));gS
hA-=2;Lml:dZ
Lmm:gJ
d6;Lmn:o5
Lmo:q3
TailCall_cMul;Laf:gA
dG
4));Lmp:qM
q5
h2
Lag:qE=x+qA(1);gY
Lel:gJ
d6;q3
Lmo;Lah:dP
cSub;Lmq:q3
hE;Lai:gL
dZ
Lna:o5
Lnb:q3
oA;Laj:gL
g2
q4
Lnc:d1
Lnd:qF
cRSub);g7
Lak:hJ
gS
o1
dZ
q3
Lnc;Lal:gL
dZ
q3
Lnd;Lam:gL
hI
q4
Lne:d1
Lnf:qF
B);Lng:gJ
cSub;qQ
Lmq;Lan:hJ
q0
d3
Lne;Lao:gL
g2
q4
q3
Lnf;Lap:qR
y+x;Laq:qT
Lbo:hF
q4
g7
Lba:qT
g2
o9
oT
hU
Lnc;Lbb:q7
oD
Lnc;Lbc:qR
fp_and(x
gZ
Lbd:qE=fp_asin(mX
Lbe:qE=fp_asinh(mX
Lbf:qE=fp_atan(mX
Lbg:qR
fp_atan2(y
h0
Lbh:qE=fp_atanh(mX
Lbi:qE=fp_cbrt(mX
Lbj:oG
cFloor);Lnh:gJ
cNeg;qQ
hD;Lbk:qE=fp_ceil(mX
Lbl:q0
gF
Lni:q3
TailCall_cCos;Lbm:qE=fp_cos(mX
Lbn:dO
TailCall_cCosh;Lbp:oG
cSqr);dG
1));Lnj:oB
d1
Lnk:gJ
cSqrt;qQ
TailCall_cSqrt;Lbq:qE=fp_cosh(mX
Lca:qE=RadiansToDegrees(mX
Lcb:oG
cSec
h2
Lcc:oG
cTan
h2
Lcd:oG
cSin
h2
Lce:dG
0));q0[0]o1
Lnl:qF
d6);dG
1));Lnm:oB
Lnn:gJ
oI;q3
Lna;Lcf:oG
cNeg);qF
cExp
h2
Lcg:oG
cNeg);qF
dA
h2
Lch:dO
Lel;Lci:oG
cNeg);qF
cPow
h2
Lcj:oG
cCos
h2
Lck:oG
cCsc
h2
Lcl:oG
cCot
h2
Lcm:q7
hY
Lno:gJ
cDeg;qQ
TailCall_cDeg;Lcn:q7
hY
Lnp:gJ
cRad;qQ
TailCall_cRad;Lco:qR
y/x
oR
q3
Lml;Lcp:hJ
qS
hA
gF
Lnq:q3
o0;Lcq:qR
y/x;q3
oM
Lda:qE=qA(1)/x;q3
Lel;Ldb:q7
o9
qF
d6);Loa:qQ
Lnq;Ldc:qT
g2
o9
qF
d6);oT
oB
Lob:gJ
cRDiv;qQ
TailCall_cRDiv;Ldd:g2
o9
qF
d6);qF
B
gI
Lob;Lde:qS
hA
gF
Loc:q3
dV;Ldf:qR
fp_equal(y
h0
Ldg:qT
q7
q1
cExp);qB
dX)gI
Lmp;Ldh:qE=dX);g7
Ldi:qT
q7
q1
dA);qB
dH)gI
Lmp;Ldj:qE=dH);g7
Ldk:qB
dB
qA(2)));oB
Lod:qF
d6);gJ
cExp;qQ
TailCall_cExp;Ldl:oG
cCeil
gI
Lnh;Ldm:qE=fp_floor(mX
Ldn:qR
fp_less(x
gZ
Ldo:qT
oG
cNeg);Ljg:qF
cAbsNot);g7
Ldp:qE=qA(0.5)/x;qS=oF);Loe:qF
d9);g7
Ldq:qR
fp_lessOrEq(x
gZ
Lea:qT
Lin:hF
q4
Lof:qF
cAbsNotNot);g7
Leb:qE=fp_int(mX
Lec:oG
cSec);g7
Led:dP
cTan;Log:q3
dQ;Lee:dP
cSin;Loh:q3
dN;Lef:oG
cNeg);gJ
cPow;Loi:o5
Loj:q3
TailCall_cPow;Leg:dP
cCos;q3
Lni;Leh:oG
cCsc);g7
Lei:oG
cRSqrt);g7
Lej:oG
cCot);g7
Lek:qE=qA(1)/x;g7
Lem:qE=qA(0.5)/x;qS=oF);gJ
cNot;o5
Lok:q3
TailCall_cNot;Len:qR
fp_less(y
h0
Leo:qT
Lio:gK
Ljg;Lep:qR
fp_lessOrEq(y
h0
Leq:qT
oG
cNeg
gI
Lof;Lfa:qT
q7
q1
cLog);qB
dB
qF1
Lfb:oG
d4
qF
cLog);Lol:qM
dY
gI
Lnn;Lfc:qE=dB
mX
Lfd:qB
d5
fp_const_e<qA>()));Lom:q0[0]o1
q3
Lmm;Lfe:qT
q7
q1
w0);qB
d5
qF1
Lff:oG
d4
qF
w0
gI
Lol;Lfg:qE=d5
mX
Lfh:qB
hZ
fp_const_e<qA>())gI
Lom;Lfi:qT
q7
q1
oZ);qB
hZ
qF1
Lfj:oG
d4
qF
oZ
gI
Lol;Lfk:qE=hZ
mX
Lfl:qR
fp_max(x
gZ
Lfm:qR
fp_min(x
gZ
Lfn:qR
fp_mod(y
h0
Lfo:dP
cSqr;Lon:q3
TailCall_cSqr;Lfp:dP
cDiv;q3
Lnq;Lfq:g2
q1
cSqr);mV
Lnh;Lga:q7
q1
cSqr
gI
Lnh;Lgb:qE=x+qA(1);gY
gJ
cPow;q3
Loj;Lgc:gY
q3
Lmo;Lgd:qR
x;Loo:qT
dZ
q3
Lmn;Lge:q7
q6
Lop:hI
q4
Loq:qF
A);oT
Lpa:hU
Lmn;Lgf:qT
q3
Lop;Lgg:qT
hI
q1
B
gI
Loq;Lgh:qT
g2
q4
q3
Loq;Lgi:qS
o1
q3
oN
Lgj:qS
hA
gF
q3
Lmo;Lgk:qT
Lpb:g2
q4
g7
Lgl:qE=x+x;q3
Lgc;Lgm:qR
x;dK=q5
oR
gA
qF
A);oU);oB
mV
Lnn;Lgn:qR
x
oR
gU
oU
gI
Lnm;Lgo:qE=RadiansToDegrees(x
gI
Lgj;Lgp:qC1
oR
hI
q4
Lpc:qF
d6);Lpd:qF
B);gJ
cDiv;q3
Loa;Lgq:hJ
q0
d3
Lpc;Lha:qC1
qP
hY
q3
Lpd;Lhb:qT
hI
q4
q3
Lmn;Lhc:qT
gA
qB
x+x
gI
Lpa;Lhd:q7
q6
q3
Lpb;Lhe:qC1;q3
Loo;Lhf:hJ
q3
Lgj;Lhg:qC1
qP
hY
Lpe:mV
Lob;Lhh:hJ
gS
o1
dZ
q3
Lpe;Lhi:qC1
oR
dZ
q3
Lob;Lhj:qE=DegreesToRadians(x
gI
Lgj;Lhk:qR
x;dK=q5
oR
gA
qF
A);oU);oB
mV
Lng;Lhl:qC1;q3
oM
Lhm:q0[0]=dY;q2-=1
oR
Lpf:gJ
oI;q3
Lnb;Lhn:qT
gK
Lno;Lho:qT
gK
Lnp;Lhp:qT
gK
Lnh;Lhq:g2
oD
Lpc;Lia:dZ
Lpg:qF
cSqr
gI
Lmn;Lib:qT
g2
o9
oT
hU
Lpe;Lic:q7
oD
Lpe;Lid:g2
q4
q3
Lpg;Lie:qS
hA
gF
Lph:q3
TailCall_cNEqual;Lif:qR
fp_nequal(y
h0
Lig:hJ
q3
Lch;Lih:hJ
gU
gJ
cSin;qQ
Loh;Lii:hJ
gU
gJ
oV;qQ
TailCall_cSinh;Lij:hJ
gU
gJ
cTan;qQ
Log;Lik:hJ
gU
gJ
oX;qQ
TailCall_cTanh;Lil:hJ
g7
Lim:dO
Lok;Lip:dP
o8;q3
Lph;Liq:dP
hC;q3
TailCall_cLessOrEq;Lja:dP
cLess;q3
TailCall_cLess;Ljb:dP
h5;q3
TailCall_cGreaterOrEq;Ljc:dP
hS;q3
TailCall_cGreater;Ljd:dP
cEqual;q3
Loc;Lje:gK
Loe;Ljf:qE=fp_not(mX
Ljh:qR
fp_or(x
gZ
Lji:qT
q7
q1
d4
qB
x+x);Lpi:hU
Loi;Ljj:qS=q5
qP
q4
q3
Lod;Ljk:qS=oF);gJ
dA;qQ
TailCall_cExp2;Ljl:qC1
oR
dZ
q3
Loi;Ljm:qS=oF
gI
Loi;Ljn:qS
hA
gF
q3
Loj;Ljo:qT
g2
q1
d6);qB
x
gI
Lpi;Ljp:qE=qA(0
gI
Lnl;Ljq:qT
gK
Lnk;Lka:qT
hF
q4
gJ
cCbrt;qQ
TailCall_cCbrt;Lkb:qT
oG
cCbrt);Lpj:gJ
cInv;qQ
TailCall_cInv;Lkc:qT
q3
Lei;Lkd:qT
gK
Lpj;Lke:q7
q6
g2
q1
d4
oU
gI
Lpi;Lkf:qE=x+x;q3
Ljn;Lkg:qR
oH
y
h0
Lkh:qE=DegreesToRadians(mX
Lki:oG
cSin
gI
Lnh;Lkj:qE=fp_sin(mX
Lkk:oG
cSqr);dG-1)gI
Lnj;Lkl:oG
oV
gI
Lnh;Lkm:qE=fp_sinh(mX
Lkn:dO
Lon;Lko:dP
cAbs;q3
Lmk;Lkp:qE=fp_sqrt(mX
Lkq:dG
0)gI
Lom;Lla:dO
Lpf;Llb:qR
y-x;q3
oM
Llc:hJ
q3
Lpf;Lld:qT
g2
o9
d1
oT
hU
Lnd;Lle:q7
o9
qF
cSub
gI
Lnd;Llf:oG
cTan
gI
Lnh;Llg:qE=fp_tan(mX
Llh:oG
oX
gI
Lnh;Lli:qE=fp_tanh(mX
Llj:qE=fp_trunc(mX
Llk:qR
x-y;Lpk:qT
dZ
Lpl:qF
A);g7
Lll:qE=fp_tan(x);Lpm:qS=q5
qP
q4
q3
Lpl;Llm:qE=dB
x
gI
Lpm;Lln:qE=hZ
x
gI
Lpm;Llo:qE=dX
gI
Lpm;Llp:qE=oH
qA(10),x
gI
Lpm;Llq:qE=dH
gI
Lpm;Lma:qR
x/y;q3
Lpk;Lmb:qR
x/y
oR
dZ
Lpn:qF
OppositeComparisonOpcode(A));g7
Lmc:hJ
qS=q5
qP
q4
q3
Lpn;Lmd:qR
oH
x,1/y
gI
Lpk;Lme:qE=fp_asinh(x
gI
Lpm;Lmf:qT
q7
q1
d4
qB
fp_sqrt(x));hU
Lpl;Lmg:qE=fp_atanh(x
gI
Lpm;Lmh:qM
dY);g7
Lmi:q0[0]=dY;g7
Lmj:qM
dW);g7
g7
q3
TailCall_cAcos;q3
TailCall_cAcosh;q3
TailCall_cAnd;q3
TailCall_cAsin;q3
TailCall_cAsinh;q3
TailCall_cAtan;q3
TailCall_cAtan2;q3
TailCall_cAtanh;q3
TailCall_cCeil;q3
TailCall_cFloor;q3
TailCall_cInt;q3
TailCall_cLog;q3
TailCall_cLog10;q3
TailCall_cLog2;q3
TailCall_cMax;q3
TailCall_cMin;q3
TailCall_cMod;q3
TailCall_cOr;q3
TailCall_cRDiv;q3
TailCall_cRad;q3
dN;q3
TailCall_cSinh;q3
TailCall_cSqrt;q3
hE;q3
dQ;q3
TailCall_cTanh;q3
TailCall_cTrunc;
#endif
#undef FP_ReDefinePointers
#undef FP_TRACE_BYTECODE_OPTIMIZATION
#undef FP_TRACE_OPCODENAME
