#!/bin/sh

runTest()
{
    make release_clean
    FP_FEATURE_FLAGS="$1" make testbed_release
    if [ "$?" -ne "0" ]; then exit 1; fi
    ./testbed_release
    if [ "$?" -ne "0" ]; then exit 1; fi
}

runTest "-D_GLIBCXX_DEBUG"
runTest "-D_GLIBCXX_DEBUG -DFP_ENABLE_EVAL"
runTest "-D_GLIBCXX_DEBUG -DFP_ENABLE_EVAL -DFP_SUPPORT_ASINH"
runTest "-D_GLIBCXX_DEBUG -DFP_ENABLE_EVAL -DFP_SUPPORT_ASINH -DFP_NO_EVALUATION_CHECKS"
runTest "-D_GLIBCXX_DEBUG -DFP_NO_SUPPORT_OPTIMIZER"
runTest "-D_GLIBCXX_DEBUG -DFP_ENABLE_EVAL -DFP_SUPPORT_ASINH -DFP_NO_SUPPORT_OPTIMIZER"
runTest "-D_GLIBCXX_DEBUG -DFP_USE_THREAD_SAFE_EVAL"
runTest "-D_GLIBCXX_DEBUG -DFP_USE_THREAD_SAFE_EVAL_WITH_ALLOCA"
runTest "-D_GLIBCXX_DEBUG -DFP_ENABLE_EVAL -DFP_SUPPORT_ASINH -DFP_NO_SUPPORT_OPTIMIZER -DFP_USE_THREAD_SAFE_EVAL_WITH_ALLOCA -DFP_NO_EVALUATION_CHECKS"
runTest "-DFP_NO_EVALUATION_CHECKS"
